#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
apt-get -y update
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get update
apt-get install -y haproxy=1.8.\*

echo "
frontend http
    bind *:80
    mode http
    default_backend web-backend

backend web-backend
        balance roundrobin
        server 802-web-01 35.243.173.73 check
        server 802-web-02 34.74.64.12 check" >> /etc/haproxy/haproxy.cfg

service haproxy restart
