#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd

IFS=:
while read -r user pass uid gid desc home shell; do
	echo "The user $user is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $pass, more info about the user here: $desc"
done < /etc/passwd
