#!/usr/bin/env bash
# script that displays the time for 12 hours and 59 minutes

hour=0
while [ $hour -lt 13 ]
do
	echo "Hour: $hour"
	minutes=1
	while [ $minutes -lt 60 ]
	do
		echo "$minutes"
		(( minutes++ ))
	done
	hour=$(( hour + 1 ))
done