#!/usr/bin/env bash
#script that gives you information about the holbertonschool file

myfile="holbertonschool"

if [ -e "$myfile" ]
then
    echo "holbertonschool file exists"
    if [ ! -s "$myfile" ]
    then
        echo "holbertonschool file is empty"
    else
        echo "holbertonschool file is not empty"
    fi
    if [ -f "$myfile" ]
    then
        echo "holbertonschool is a regular file"
    fi
else
    echo "holbertonschool file does not exist"
fi
