#!/usr/bin/env bash
# nginx must be runs as nginx user and must be listening on all active IPs on port 8080
pkill apache2
chmod 766 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
